### ISSUE TITLE
"Code" is the plural form of "code"

### ISSUE THREAD

**Issue by ravern** [roytornado/Flow-iOS#1]
The plural form of "code" is "code" not "codes".

**Comment by ravern** [comment]
Examples include "Flow is an utility/ design pattern that help developers to write simple and readable *codes*. There are two main concerns: Flow of operations and Flow of data" and some more in the README

**Comment by ravern** [comment]
A stack exchange question on this matter can be found here: https://english.stackexchange.com/questions/20455/is-it-wrong-to-use-the-word-codes-in-a-programming-context

**Comment by roytornado** [comment]
Thanks!!
You are very nice.
Just revised the Readme.
